export const SET_PAGE_COL = 'SET_PAGE_COL'
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const CHANGE_STYLE_MODE = 'CHANGE_STYLE_MODE'
export const GET_INDEX_IMG = 'GET_INDEX_IMG'
export const GET_CAPTCHAURL = 'GET_CAPTCHAURL'

export const SUCCESS_GET_SNSLOGINS = 'SUCCESS_GET_SNSLOGINS'
export const FAILURE_GET_SNSLOGINS = 'FAILURE_GET_SNSLOGINS'

export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS'
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE'

export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const PRENEXT_ARTICLE = 'PRENEXT_ARTICLE'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'

export const COMMENT_LIST = 'COMMENT_LIST'
export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT'
export const SUCCESS_ADD_REPLY = 'SUCCESS_ADD_REPLY'
export const GET_COMMENT_LIST_FAILURE = 'GET_COMMENT_LIST_FAILURE'
export const SUCCESS_GET_APPS = 'SUCCESS_GET_APPS'
export const FAILURE_GET_APPS = 'FAILURE_GET_APPS'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
