// Options
export const SET_PAGE_COL = 'SET_PAGE_COL'
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'

// Tag
export const REQUEST_TAG_LIST = 'REQUEST_TAG_LIST'
export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS'
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE'

// Article List
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const CLEAR_ARTICLE_LIST = 'CLEAR_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'

// Article Hot
export const REQUEST_ARTICLE_HOT_LIST = 'REQUEST_ARTICLE_HOT_LIST'
export const GET_ARTICLE_HOT_LIST_FAILURE = 'GET_ARTICLE_HOT_LIST_FAILURE'
export const GET_ARTICLE_HOT_LIST_SUCCESS = 'GET_ARTICLE_HOT_LIST_SUCCESS'

// Article Detail
export const CLEAR_ARTICLE_DETAIL = 'CLEAR_ARTICLE_DETAIL'
export const REQUEST_ARTICLE_DETAIL = 'REQUEST_ARTICLE_DETAIL'
export const GET_ARTICLE_DETAIL_FAILURE = 'GET_ARTICLE_DETAIL_FAILURE'
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS'
